apiVersion: v1
kind: Pod
metadata:
  name: zooo1
  labels:
    app: zookeepeer
   # role: vote
   # version: v1
spec:
  containers:
    - name: zooo1
      image: digitalwonderland/zookeeper
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
          #protocol: TCP
